name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Checkout code
      uses: actions/checkout@v3

    # Ruby 설정
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    # Jekyll 의존성 설치
    - name: Install dependencies
      run: |
        cd ai-diary-site
        bundle install

    # Jekyll 빌드 실행
    - name: Build Jekyll site
      run: |
        cd ai-diary-site
        bundle exec jekyll build -d ../_site

    # GitHub Pages 배포
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
